unstable_features = true
brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = true
error_on_line_overflow = true
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
imports_indent = "Visual"
indent_style = "Visual"
license_template_path = ".licensetemplate"
match_arm_blocks = false
match_block_trailing_comma = true
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
struct_field_align_threshold = 20
tab_spaces = 2
trailing_comma = "Always"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true